# Generated by Django 3.0.1 on 2020-02-20 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20200207_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='ques',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
