# Generated by Django 3.0.1 on 2020-02-20 17:01
from __future__ import unicode_literals
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20200220_2231'),
    ]

    operations = [
    	migrations.AlterField(
            model_name='ques',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
